version: '3'
services:
  front:
    container_name: pizza_front
    build:
      context: .
      dockerfile: Dockerfile.front
    restart: unless-stopped
    environment:
      NODE_ENV: development
      REACT_APP_JSONSERVER_URL: https://pizza.al-dev.ru/api/
      PORT: 3000
    ports:
      - '3242:3000'
  server:
    container_name: pizza_db
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: unless-stopped
    environment:
      NODE_ENV: development
    ports:
      - '3243:3001'
